[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[edge_functions]]
  function = "blog-meta"
  path = "/blog.html"

[[redirects]]
  from = "/admin"
  to = "/404.html"
  status = 404
  force = true

[[redirects]]
  from = "/admin/"
  to = "/404.html"
  status = 404
  force = true

[[redirects]]
  from = "/admin/*"
  to = "/404.html"
  status = 404
  force = true
